---
- hosts: dev
  tasks:
  - name: Install apache webserver
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: start the service if it is not started
    ansible.builtin.service:
      name: httpd
      state: started

  - name: copy the index.html into webserver
    ansible.builtin.copy:
      src: /root/index.html
      dest: /var/www/html/
